providers = ["python"]
[phases.setup]
  nixPkgs = ["python3", "gcc"]
[phases.install]
  cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]
[phases.start]
  cmd = "gunicorn --bind 0.0.0.0:$PORT api.app:app"